package ptyxiakivisualization;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.RandomAccessFile;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class AddJournal extends javax.swing.JFrame {

    /**
     * Creates new form AddJournal
     */
    public AddJournal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        journal = new javax.swing.JTextField();
        science = new javax.swing.JTextField();
        field = new javax.swing.JTextField();
        subfield = new javax.swing.JTextField();
        subsubfield = new javax.swing.JTextField();
        j = new javax.swing.JLabel();
        sc = new javax.swing.JLabel();
        fi = new javax.swing.JLabel();
        subf = new javax.swing.JLabel();
        subsubf = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        journalLabel = new javax.swing.JLabel();
        scienceLabel = new javax.swing.JLabel();
        fieldLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADD JOURNAL");

        journal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                journalActionPerformed(evt);
            }
        });

        j.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        j.setText("Journal:");

        sc.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        sc.setText("Science:");

        fi.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        fi.setText("Field:");

        subf.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        subf.setText("SubField:");

        subsubf.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        subsubf.setText("SubSubField:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(j)
                        .addGap(18, 18, 18)
                        .addComponent(journal, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(sc)
                        .addGap(18, 18, 18)
                        .addComponent(science, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(fi)
                        .addGap(18, 18, 18)
                        .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(subf)
                        .addGap(18, 18, 18)
                        .addComponent(subfield, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(subsubf)
                        .addGap(18, 18, 18)
                        .addComponent(subsubfield, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(journal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(science, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sc))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subf))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subsubfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subsubf))
                .addGap(13, 13, 13))
        );

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(61, 3, 247));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        journalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        journalLabel.setText("* required field ");

        scienceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        scienceLabel.setText("* required field");

        fieldLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fieldLabel.setText("* required field");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButton1)
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(journalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(115, 115, 115))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(scienceLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fieldLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(journalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scienceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void journalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_journalActionPerformed
        // TOD add your handling code here:
    }//GEN-LAST:event_journalActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String journal1 = journal.getText();
            //System.out.println("journal:" + journal1);
            if (journal1.equals("")) {
                throw new IllegalArgumentException(("First three fields are required!"));
            }
            String science1 = AddJournal.science.getText();
            if (science1.equals("")) {

                throw new IllegalArgumentException(("First three fields are required!!"));
            }
            String field1 = field.getText();
            if (field1.equals("")) {

                throw new IllegalArgumentException(("First three fields are required!"));
            }
            String subfield1 = subfield.getText().trim();
            String subsubfield1 = subsubfield.getText().trim();

            //=============remove </reserarch> to write new journal==============
            String fileName = "JournalScienceMatch.xml";

            List<String> lines = new ArrayList<>();

            // read the file into lines
            BufferedReader r = new BufferedReader(new FileReader(fileName));
            String in;
            while ((in = r.readLine()) != null) {
                if(!in.equals("")){
                lines.add(in);
                }
            }
            r.close();

            // check your condition
//            String secondFromBottom = lines.get(lines.size() - 2);
//            if (secondFromBottom.matches("Hello World!")) {
                lines.remove(lines.size() - 1);
//                lines.add("My fixed string");
//            }

            // write it back
            PrintWriter w = new PrintWriter(new FileWriter(fileName));
            for (String line : lines) {
                
                if(line.trim().equals("</journal>")){
                    w.println(line);
                    w.println();  
                }else{
                    w.println(line);
                }
                
            }
            w.close();

            //boolean successful = tempFile.renameTo(inputFile);
            try (PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter("JournalScienceMatch.xml", true)))) {

                out.println("<journal>");
                out.println("\t<title>" + journal1 + "</title>");
                out.println("\t<science>" + science1 + "</science>");
                out.println("\t<field>" + field1 + "</field>");
                if (!subfield1.equals("")) {
                    out.println("\t<subfield>" + subfield1 + "</subfield>");
                }
                if (!subsubfield1.equals("")) {
                    out.println("\t<subsubfield>" + subsubfield1 + "</subsubfield>");
                }
                out.println("</journal>");
                out.println("</research>");
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "The journal submitted succesfully!");
                out.close();
            } catch (IOException e) {
                System.out.println(e.toString());
            }
        } catch (IllegalArgumentException i) {
            JOptionPane.showMessageDialog(null, i.getMessage());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AddJournal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AddJournal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddJournal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddJournal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddJournal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddJournal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddJournal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fi;
    protected static javax.swing.JTextField field;
    private javax.swing.JLabel fieldLabel;
    private javax.swing.JLabel j;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    protected static javax.swing.JTextField journal;
    protected static javax.swing.JLabel journalLabel;
    private javax.swing.JLabel sc;
    protected static javax.swing.JTextField science;
    protected static javax.swing.JLabel scienceLabel;
    private javax.swing.JLabel subf;
    protected static javax.swing.JTextField subfield;
    private javax.swing.JLabel subsubf;
    protected static javax.swing.JTextField subsubfield;
    // End of variables declaration//GEN-END:variables
}
